### ISSUE TITLE
Depricated APIs and Studi Independen API Support

### ISSUE THREAD

**Issue by kaenova** [ShinyQ/Kampus-Merdeka-Reports-Crawler#1]
Hello @ShinyQ, loves your repo but I think there are APIs that already change and it seems the script is only for Kampus Merdeka Magang? I could update this repo to also support Kampus Merdeka Studi Independen. What do you think?

**Comment by ShinyQ** [comment]
Hello thank you for your interest. Yes absolutely you can update the repo and i have an advice to change the export file into excelnot in csv so we can copy and paste it more easily.

**Comment by kaenova** [comment]
Okay will working on it
